#!/bin/sh /etc/rc.common
#
# Copyright (c) 2015, 2020, The Linux Foundation. All rights reserved.
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: ISC

START=40
USE_PROCD=1

validate_skb_recycler_section() {
	uci_validate_section skb_recycler skb "${1}" \
		'max_skbs:uinteger' \
		'max_spare_skbs:uinteger' \
		'skb_recycler_enable:uinteger'

	return $?
}

skb_recycler_config() {
	local cfg="$1"

	local max_skbs max_spare_skbs skb_recycler_enable

	validate_skb_recycler_section "${1}" || {
		echo "validation failed"
		return 1
	}

	[ -n "$max_skbs" ] && echo "$max_skbs" > /proc/net/skb_recycler/max_skbs
	[ -n "$max_spare_skbs" ] && echo "$max_spare_skbs" > /proc/net/skb_recycler/max_spare_skbs
	[ -n "$skb_recycler_enable" ] && echo "$skb_recycler_enable" > /proc/net/skb_recycler/skb_recycler_enable
	[ "$skb_recycler_enable" -eq 0 ] && echo 1 > /proc/net/skb_recycler/flush
}

reload_service() {
	config_load skb_recycler
	config_foreach skb_recycler_config skb
}

start_service() {
	reload_service
}

